Quiz ui fix
VIS490/VIS-490-Sprint2 pull request #7
Opened 2020-11-16 17:23 UTC by rpasricha45

1. added matieral ui usestyle to Questions components , to style and fix issue 
2. added Paper matieral UI component , to allow for scrolling for the quiz page

2020-11-16 21:50 UTC, vkoli requested changes
A few additional points:
1) Add in you change to App.js in this commit
2) Is it possible to have the Quiz div take up the remaining screen width? Right now the component stops somewhere before.

2020-11-16 21:50 UTC, vkoli commented on src/components/Question.js
> +
Comments should be removed
Space between answer label and radio button is ok.

2020-11-16 21:50 UTC, vkoli commented on src/components/Question.js
>  				name={props.questionName}
Can you also look into increasing the size the Question text in the Form Label component?
At Line 42.

2020-11-16 21:50 UTC, vkoli commented on src/components/Quiz.js
>            </li>
Is it possible to get ride of the list-style? Right now its showing bullet points which doesn't really look clean necessarily. 
If not, just change the li tag to ol for numbered list.

2020-11-17 15:21 UTC, rpasricha45 commented
I removed the comments , + bullpoints , and made the overall quiz wider to make look nicer ,  I  didn't get to make the text bigger yet stuck on this part

2020-11-17 23:35 UTC, vkoli commented
What we have for the quiz ui right now is sufficient for this week, so we can close this branch

2020-11-17 23:35 UTC, merged